// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgxFpKc1L3zUvPX7z_WNbV5-gkb152C7A',
    appId: '1:351289879356:web:9364c078e1d94042a20c39',
    messagingSenderId: '351289879356',
    projectId: 'instagram-clone-master-67b82',
    authDomain: 'instagram-clone-master-67b82.firebaseapp.com',
    databaseURL: 'https://instagram-clone-master-67b82-default-rtdb.firebaseio.com',
    storageBucket: 'instagram-clone-master-67b82.appspot.com',
    measurementId: 'G-N2Q2MYTENX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwx6Ori31M8esnrbn4EPrEsywiHMubQso',
    appId: '1:351289879356:android:4c97f952a50d1765a20c39',
    messagingSenderId: '351289879356',
    projectId: 'instagram-clone-master-67b82',
    databaseURL: 'https://instagram-clone-master-67b82-default-rtdb.firebaseio.com',
    storageBucket: 'instagram-clone-master-67b82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEoK9trwyE6wExEw47-Fgc76ABXRs7iks',
    appId: '1:351289879356:ios:b15c954d02b1ae38a20c39',
    messagingSenderId: '351289879356',
    projectId: 'instagram-clone-master-67b82',
    databaseURL: 'https://instagram-clone-master-67b82-default-rtdb.firebaseio.com',
    storageBucket: 'instagram-clone-master-67b82.appspot.com',
    iosClientId: '351289879356-45l68nl0i54aohlsl339a9jm2emn2re7.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEoK9trwyE6wExEw47-Fgc76ABXRs7iks',
    appId: '1:351289879356:ios:b15c954d02b1ae38a20c39',
    messagingSenderId: '351289879356',
    projectId: 'instagram-clone-master-67b82',
    databaseURL: 'https://instagram-clone-master-67b82-default-rtdb.firebaseio.com',
    storageBucket: 'instagram-clone-master-67b82.appspot.com',
    iosClientId: '351289879356-45l68nl0i54aohlsl339a9jm2emn2re7.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
